apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
data:
  DATABASE_HOST: {{ required "DatabaseAddress" .Values.DatabaseAddress | quote }}
  DATABASE_PORT: {{ required "DatabasePort" .Values.DatabasePort | quote }}
  DATABASE_SCHEMA: {{ required "DatabaseSchema" .Values.DatabaseSchema | quote }}
  DATABASE_USERNAME: {{ required "DatabaseUsername" .Values.DatabaseUsername | quote }}
  CACHE_HOST: {{ required "RedisAddress" .Values.RedisAddress | quote }}
  CACHE_PORT: {{ required "RedisPort" .Values.RedisPort | quote }}
  CACHE_DB: {{ required "RedisDatabase" .Values.RedisDatabase | quote }}
  CFG_SECRET_KEY: {{ randAlphaNum 30 | b64enc | quote }}
  CFG_EMAIL_HOST: {{ required "SmtpHost" .Values.SmtpHost | quote }}
  CFG_EMAIL_HOST_USER: {{ required "SmtpUser" .Values.SmtpUser | quote }}
  ALLOWED_HOSTS: {{range $i, $elem := .Values.Endpoints}}{{if $i}},{{end}}{{$elem}}{{end}}
  CFG_MEDIA_BUCKET: {{ required "MediaBucket" .Values.MediaBucket | quote }}
  CFG_SERVER_EMAIL: {{ required "ServerEmail" .Values.ServerEmail | quote }}
  CFG_AWS_S3_CUSTOM_DOMAIN: {{ required "AwsS3CustomDomain" .Values.AwsS3CustomDomain | quote }}
  {{ if BasicAuthRealm }}
  BASIC_AUTH_REALM: {{ .Values.BasicAuthRealm | qote }}
  BASIC_AUTH_USER: {{ .Values.BasicAuthUser | quote }}
  BASIC_AUTH_PASS: {{ .Values.BasicAuthPass | quote }}
  {{ end }}
  ES_INDEX: {{ required "ElasticSearchIndex" .Values.ElasticSearchIndex | quote }}
  ES_HOST: {{ required "ElasticSearchEndpoint5" .Values.ElasticSearchHost | quote }}
  ES_ACCESS_KEY_ID: {{ required "ElasticSearchAccessKey" .Values.ElasticSearchAccessKey | quote }}
  ES_REGION: {{ required "Region" .Values.Region | quote }}
  RECAPTCHA_PUBLIC_KEY: {{ required "RecaptchaPublicKey" .Values.RecaptchaPublicKey | quote }}
  HARP_API_USERNAME: {{ required "HarpApiUsername" .Values.HarpApiUsername | quote }}
  GOOGLE_TAG_MANAGER_ID: {{ required "GoogleTagManagerId" .Values.GoogleTagManagerId | quote }}
  CFG_RAVEN_DSN: {{ required "RavenDsn" .Values.RavenDsn | quote }}


