apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ required "A valid number of replicas is required" .Values.Replicas }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              topologyKey: failure-domain.beta.kubernetes.io/zone
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - {{ .Release.Name }}
      containers:
      - name: hra
        image: {{ required "A valid DockerRegistry is required" .Values.DockerRegistry }}/hra
        ports:
        - containerPort: 80
        {{- include "environment" . | indent 8 }}
