apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redirector
  labels:
    app: {{ .Release.Name }}-redirector
spec:
  ports:
  - port: 80
  selector:
    app: {{ .Release.Name }}-redirector
